export const keys = [
  'Ácido Linoleico',
  'Ácido Linolênico',
  'Açúcar Total',
  'Cálcio',
  'Carboidrato',
  'Cobalamina',
  'Cobre',
  'Colesterol',
  'Calorias',
  'Ferro',
  'Fibra Total',
  'Folato DFE',
  'Fósforo',
  'Gordura Monossaturada',
  'Gordura Polissaturada',
  'Gordura Saturados',
  'Gordura Trans Total',
  'Lipídios Totais',
  'Magnésio',
  'Manganês',
  'Niacina NE',
  'Niacina',
  'Piridoxina',
  'Potássio',
  'Proteína',
  'Retinol',
  'Riboflavina',
  'Selênio',
  'Sódio',
  'Tiamina',
  'Vitamina A',
  'Vitamina C',
  'Vitamina D',
  'Vitamina E',
  'Zinco',
];
const values = [
  'acidoLinoleico_g',
  'acidoLinolenico_g',
  'acucarTotal_g',
  'calcio_mg',
  'carboidrato_g',
  'cobalamina_mcg',
  'cobre_mg',
  'colesterol_mg',
  'energia_kcal',
  'ferro_mg',
  'fibraTotal_g',
  'folato_DFE_mcg',
  'fosforo_mg',
  'gorduraMonossaturada_g',
  'gorduraPolissaturada_g',
  'gorduraSaturados_g',
  'gorduraTransTotal_g',
  'lipidiosTotais_g',
  'magnesio_mg',
  'manganes_mg',
  'niacina_NE_mg',
  'niacina_mg',
  'piridoxina_mg',
  'potassio_mg',
  'proteina_g',
  'retinol_mcg',
  'riboflavina_mg',
  'selenio_mcg',
  'sodio_mg',
  'tiamina_mg',
  'vitaminaA_mcg',
  'vitaminaC_mg',
  'vitaminaD_mcg',
  'vitaminaE_mg',
  'zinco_mg',
];

const map = new Map();

for (let i = 0; i < keys.length; i += 1) {
  map.set(keys[i], values[i]);
}
export default map;
