const vd = {
  'energia-kcal': '2000',
  'proteina-g': '50',
  'lipidiosTotais-g': '55',
  'carboidrato-g': '300',
  'fibraTotal-g': '25',
  'colesterol-mg': '300',
  'gorduraSaturados-g': '22',
  'gorduraMonossaturada-g': '0',
  'gorduraPolissaturada-g': '0',
  'acidoLinoleico-g': '15',
  'acidoLinolenico-g': '2',
  'gorduraTransTotal-g': '0',
  'acucarTotal-g': '50',
  'acucarAdicao-g': '0',
  'calcio-mg': '1000',
  'magnesio-mg': '260',
  'manganes-mg': '2.3',
  'fosforo-mg': '700',
  'ferro-mg': '18',
  'sodio-mg': '2000',
  'sodioAdicao-mg': '0',
  'potassio-mg': '4700',
  'cobre-mg': '900',
  'zinco-mg': '11',
  'selenio-mcg': '55',
  'retinol-mcg': '800',
  'vitaminaA-mcg': '800',
  'tiamina-mg': '1.2',
  'riboflavina-mg': '1.3',
  'niacina-mg': '16',
  'niacina-NE-mg': '15',
  'piridoxina-mg': '1.3',
  'cobalamina-mcg': '2.4',
  'folato-DFE-mcg': '400',
  'vitaminaD-mcg': '5',
  'vitaminaE-mg': '15',
  'vitaminaC-mg': '45',
};

export default vd;
